### ISSUE TITLE
OpenSSL pkg-config misrequired on FreeBSD 10.2p14

### ISSUE THREAD

**Issue by smjones** [trusteddomainproject/OpenARC#1]
There's a dependency on a pkg-config utility from the OpenSSL package that doesn't appear to be present on FreeBSD 10.2. Also involves use of the AC_MSG_WARN macro. I removed the relevant stanza from configure while the autoconf scaffolding is being updated, diff attached because why not?

FreeBSD ($HOSTNAME) 10.2-RELEASE-p14 FreeBSD 10.2-RELEASE-p14 #0: Wed Mar 16 20:46:12 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

[configure.diff.txt](https://github.com/mskucherawy/OpenARC/files/285229/configure.diff.txt)

**Comment by martinbogo** [comment]
Cleaning up / closing old issues.  Will add this to regression tests against FreeBSD and OpenBSD when creating a new release.
