### ISSUE TITLE
Installation how-to

### ISSUE THREAD

**Issue by arnoldasb** [trusteddomainproject/OpenARC#10]
Hi,
where do I find installation document? I want to try this out, but how do I install and use it on Linux ?

**Comment by arnoldasb** [comment]
```
sudo yum install libtool libbsd-devel openssl-devel libopendkim-devel.x86_64 sendmail-milter.x86_64 sendmail-devel.x86_64 -y

# git clone https://github.com/mskucherawy/OpenARC

# autoreconf -fvi
# ./configure
# make
```

```
Though I've ended up in errors

Making all in docs
make[2]: Entering directory `/opt/OpenARC/docs'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/opt/OpenARC/docs'
Making all in openarc
make[2]: Entering directory `/opt/OpenARC/openarc'
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -pthread  -g -O2  -L/usr/lib -pthread  -o openarc openarc-config.o openarc-openarc.o openarc-openarc-ar.o openarc-openarc-crypto.o openarc-openarc-test.o openarc-util.o ../libopenarc/libopenarc.la -lmilter -lssl -lcrypto    -lresolv -lbsd
libtool: link: gcc -std=gnu99 -pthread -g -O2 -pthread -o .libs/openarc openarc-config.o openarc-openarc.o openarc-openarc-ar.o openarc-openarc-crypto.o openarc-openarc-test.o openarc-util.o  -L/usr/lib ../libopenarc/.libs/libopenarc.so -lmilter -lssl -lcrypto -lresolv -lbsd -pthread -Wl,-rpath -Wl,/usr/local/lib
openarc-openarc.o: In function `arcf_config_setlib':
/opt/OpenARC/openarc/openarc.c:1708: undefined reference to `arc_options'
/opt/OpenARC/openarc/openarc.c:1722: undefined reference to `arc_options'
/opt/OpenARC/openarc/openarc.c:1693: undefined reference to `arc_init'
openarc-openarc.o: In function `arcf_cleanup':
/opt/OpenARC/openarc/openarc.c:2020: undefined reference to `arc_free'
openarc-openarc.o: In function `mlfi_eoh':
/opt/OpenARC/openarc/openarc.c:2993: undefined reference to `arc_message'
/opt/OpenARC/openarc/openarc.c:3049: undefined reference to `arc_header_field'
/opt/OpenARC/openarc/openarc.c:3066: undefined reference to `arc_eoh'
openarc-openarc.o: In function `mlfi_eom':
/opt/OpenARC/openarc/openarc.c:3209: undefined reference to `arc_eom'
/opt/OpenARC/openarc/openarc.c:3282: undefined reference to `arc_getseal'
/opt/OpenARC/openarc/openarc.c:3303: undefined reference to `arc_hdr_next'
/opt/OpenARC/openarc/openarc.c:3309: undefined reference to `arc_hdr_name'
/opt/OpenARC/openarc/openarc.c:3314: undefined reference to `arc_hdr_value'
openarc-openarc.o: In function `arcf_config_free':
/opt/OpenARC/openarc/openarc.c:1285: undefined reference to `arc_close'
openarc-openarc.o: In function `main':
/opt/OpenARC/openarc/openarc.c:3653: undefined reference to `arc_ssl_version'
/opt/OpenARC/openarc/openarc.c:3655: undefined reference to `arc_ssl_version'
/opt/OpenARC/openarc/openarc.c:4518: undefined reference to `arc_close'
collect2: error: ld returned 1 exit status
make[2]: *** [openarc] Error 1
make[2]: Leaving directory `/opt/OpenARC/openarc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/OpenARC'
make: *** [all] Error 2
```

**Comment by arnoldasb** [comment]
While browsing github I've noticed new pull request, so kudos to https://github.com/flowerysong
```
# git clone https://github.com/flowerysong/OpenARC.git
# cd OpenARC
# git checkout build-fixes
# autoreconf -fvi
# ./configure
# make
# make install
```

```
openarc -V
openarc: OpenARC Filter v0.1.0
	Compiled with OpenSSL 1.0.1e-fips 11 Feb 2013
	SMFI_VERSION 0x1000001
	libmilter version 1.0.1
	libopenarc 0.1.0:
```

Let's copy the config sample
```
mkdir /etc/openarc
cp /usr/local/share/doc/openarc/openarc.conf.sample /etc/openarc/openarc.conf
```

> For the sake of showing intended format and content, the OpenDKIM equivalent is:
> https://sourceforge.net/p/opendkim/git/ci/master/tree/opendkim/opendkim.conf.sample


I've change the port to 8991 so it does not conflict if you are already running opendkim on 8891
```
# cat /etc/openarc/openarc.conf
# This is a simple config file for OpenARC
Syslog                  yes
Socket                  inet:8991@localhost
PidFile			/var/run/opendkim/openarc.pid
```

Let's check our config
```
# openarc -c /etc/openarc/openarc.conf -n
openarc: /etc/openarc/openarc.conf: required parameter "Domain" missing
```

Okay it's missing something for the moment

**Comment by AntiFreeze** [comment]
Here's a functional openarc.conf:

# This is a simple config file for OpenARC

KeepTemporaryFiles 	  yes

Syslog			  yes
Domain			  example.com
Selector		  example
KeyFile			  /var/db/milter-opendkim/example.private

SignatureAlgorithm	  rsa-sha256

UserID			  mail

Socket			  inet:8891@localhost

PidFile			  /var/run/milter-openarc/openarc.pid

**Comment by grawity** [comment]
Trying to follow the above on my own mailserver – it's unclear to me, do I need just OpenARC, or both OpenARC & regular OpenDKIM?

**Comment by arnoldasb** [comment]
Usually you need both, OpenARC and OpenDKIM. Though in ESP use case it's not clear for me yet, how to use, operate OpenARC.

**Comment by mskucherawy** [comment]
Eventually there will be READMEs and INSTALL files to assist you.  I'll leave this open until they're done.

The package is still in Alpha development, so some things you would expect to see in a mature project are still to be created.

**Comment by arunksasi** [comment]
openarc: error while loading shared libraries: libopenarc.so.0: cannot open shared object file: No such file or directory

May I know why I am getting this error?

**Comment by thew0mble** [comment]
I have opendkim and opendmarc working on postfix, would like have a play using openarc.

So reading the thread I see I need to install

"sudo yum install libtool libbsd-devel openssl-devel libopendkim-devel.x86_64 \ 
sendmail-milter.x86_64 sendmail-devel.x86_64 -y"

Do I still install "sendmail-milter.x86_64 sendmail-devel.x86_6" given I will be using postfix not sendmail?

**Comment by xpunkt** [comment]
i played little more with it :=)

i would like to configure one instance for verify only mode, but current openarc does not yet support mode v only config, it gives error on missing keyfile, missing selector....

for openarc signing, how to create the keyfile ?, is it just opendim-genkey and upload it just like its done in opendkim ?

what dns rr is used by openarc ?

**Comment by jcbf** [comment]
This is something that should be included in the README or INSTALL.

According to https://tools.ietf.org/html/draft-ietf-dmarc-arc-protocol-10#section-4.1.6 , it's the same for both Keys and DNS RR.

Additional look at https://tools.ietf.org/html/draft-ietf-dmarc-arc-protocol-10#section-8.1

>    DKIM-Signatures SHOULD never sign any ARC header fields.

I read this as 

> Don't use the same key for DKIM and ARC signing

**Comment by fvdm** [comment]
@jcbf or exclude the ARC headers from signing with DKIM.

If I understand the concept of ARC correctly, DKIM is intended for signing the message itself and the directly related headers, while ARC is the verification chain which can change anywhere on the route to delivery. That would invalidate the DKIM signature even though the message and its headers remain perfectly intact.

However, I’m just getting into ARC and there is not much clear information available. So I may be wrong.

**Comment by juh** [comment]
@jbbf:No, it means what it says: Don't sign ARC headers.
Of course you can reuse your DKIM key for ARC.

**Comment by hellracer** [comment]
openarc-genkey is missing during the compilation, how can we built this?

**Comment by hellracer** [comment]
anyone successfully test this? i'm fairly confuse how to generate KeyFile

**Comment by wioxjk** [comment]
@hellracer 
You should be able to use the same keys as you use for your DKIM deployment as @juh said above.

But yes, I do not get the configfile actually, so I run openarc in v mode only. 
I have yet to find out how to actually sign the email in a proper way.

**Comment by SnailShea** [comment]
Hopefully this helps someone: unlike OpenDKIM with KeyTable in the configuration, if you're sending from multiple domains on one server you'll have to add a `KeyFile <file>` entry for each domain and specify each `Domain` entry individually. I'm not sure if this is the "correct" way to do things, nor am I entirely certain that my configuration is 100% correct, but testing against a gmail account with two sender domains gives me a `cv=none` for `i=1` and a `cv=pass` for `i=2` and so on, so I'm going to assume all is well.

**Comment by immae** [comment]
Hi @MxLinux thanks for your information. I have a server that handles multiple domains too, but what you describe doesn’t correspond to the code I see. As far as I understand the code, only the last "Domain" will be taken into account and the other ones will be ignored (the config value will be overwritten). Can you be more specific to how you configured openarc, like giving an example?
Thanks!

**Comment by SnailShea** [comment]
Currently I have only tested with accounts attached to two of the four domains I have configured. 

```
AuthservID              mail.<redacted>
AutoRestart             Yes
AutoRestartCount        10
AutoRestartRate         10/1h
Background              Yes
BaseDirectory           /var/run/openarc
Canonicalization        relaxed/simple
Domain                 <redacted>
Domain                  <redacted>
Domain                  <redacted>
Domain                  <redacted>
# EnableCoredumps       no
# FixedTimestamp        1234567890
InternalHosts           refile:/etc/opendkim/trusted.hosts
KeyFile                 /etc/opendkim/keys/<redacted>.private
KeyFile                 /etc/opendkim/keys/<redacted>.private
KeyFile                 /etc/opendkim/keys/<redacted>.private
KeyFile                 /etc/opendkim/keys/<redacted>.private
KeepTemporaryFiles      no
# MaximumHeaders        n
MilterDebug             1
Mode                    sv
# OversignHeaders       header1,header2,...
# PeerList              filenme
PidFile                 /var/run/openarc/openarc.pid
Selector                201902
SignatureAlgorithm      rsa-sha256
# SignHeaders           header1,header2,...
Socket                  inet:8991@localhost
SoftwareHeader          No
Syslog                  Yes
SyslogFacility          mail
TemporaryDirectory      /etc/openarc/tmp
UserID                  <redacted>
```

For a domain ending in .club:
![club](https://user-images.githubusercontent.com/2219973/54361013-7f588300-463c-11e9-8709-cbaa86c12c2e.png)

For another domain ending in .net:
![net](https://user-images.githubusercontent.com/2219973/54361022-8384a080-463c-11e9-8593-60f4c1c6d519.png)

What configuration are you using to handle multiple domains?

**Comment by immae** [comment]
Thanks @MxLinux it turns out we’re not talking about the same thing. The fields you hid in your are written by google, not by your server. I’m talking about what you have in your example "d=google.com" (in the ARC-Seal part). In a situation where for instance I am foo@foreign1.com, I write to bar@mydomain1.com which redirects to baz@foreign2.com. Same situation with bar2@mydomain2.com. In that situation, my server is responsible for mydomain1.com and mydomain2.com, and he is the one who needs to write this ARC-Seal header.

When foreign2 receives the emails, it comes from my server, and I wanted to put mydomain1.com or mydomain2.com in this "d" field depending on where the email was targeted. But it looks like it’s not feasible, and your suggestion just takes the last one as I predicted, ignoring the other "Domain" fields.
But actually after a closer look at the specification, it is not a problem and this field is not important, so I leave it to some ad-hoc value.

**Comment by SnailShea** [comment]
The d=, if I'm not mistaken, simply correlates to the domain doing the signing of that specific transaction. Unless your domains are being handled by multiple servers I believe each domain you control is going to skip validation when speaking with each other because your server should be included among the trusted hosts (or peers if you've split the domains among multiple servers). That said I haven't read the full content of the relevant RFCs so I could be totally off base here

**Comment by gene-git** [comment]
Multiple Domain and Keyfile lines fails totally - only the last one is used for each.

Can you guys support keytable and signingtable just like opendkim does please?

**Comment by HLFH** [comment]
> Multiple Domain and Keyfile lines fails totally - only the last one is used for each.
> 
> Can you guys support keytable and signingtable just like opendkim does please?

@gene-git I created a separate issue here: https://github.com/trusteddomainproject/OpenARC/issues/122

**Comment by martinbogo** [comment]
Duplicate of #118 ... An "install" or "build" file will be added during the next release roll-up.  Closing this old issue.

**Comment by apezio** [comment]
> INPUT_MAIL_FILTER(`milter-openarc', `S=inet:8891@localhost, F=T, T=R:2m')

This line is missing backticks because github is interpreting them as code tags.  I can't get it to show a correct line, but there should be a backtick before "milter-openarc" and before "S=inet"
