### ISSUE TITLE
sendmail reports header syntax error, no ARC- headers emitted

### ISSUE THREAD

**Issue by mdomsch** [trusteddomainproject/OpenARC#100]
Since enabling openarc, I get these messages in sendmail maillog, and no ARC-headers are emitted.

Milter insert (1): header:  ARC-Message-Signature: ...
Milter insert (1): header:  ARC-Seal: ...
Milter insert (1): header: Authentication-Results: ...
SYSERR(root): header syntax error, line "?"
SYSERR(root): header syntax error, line "?"
SYSERR(root): header syntax error, line "?"

It appears to be trying to emit the proper headers, but fails for some reason.

Using commit 8a5a4b0a278b21fe73329eebf954a1281c389b53
sendmail-milter-8.14.7-5.el7.x86_64
sendmail-cf-8.14.7-5.el7.noarch
sendmail-devel-8.14.7-5.el7.x86_64
sendmail-8.14.7-5.el7.x86_64
on CentOS 7.x (latest packages)

**Comment by AntiFreeze** [comment]
@mdomsch can you post your openarc config?

**Comment by mdomsch** [comment]
PidFile /var/run/openarc/openarc.pid
Syslog  yes
UserID  openarc:openarc
Socket  local:/var/run/openarc/openarc.sock
Mode    sv
Domain domsch.com
KeyFile /etc/openarc/keys/domsch.com/seal-20170618.private
Selector seal-20170618
SignatureAlgorithm rsa-sha256
MilterDebug 6
EnableCoredumps yes

**Comment by andreasschulze** [comment]
I see ARC- headers are added starting with a space. Is this the same issue?

**Comment by andreasschulze** [comment]
I think, [this ist the problem](https://github.com/trusteddomainproject/OpenARC/blob/develop/openarc/openarc.c#L3676)

noleadspc should act on a header*value*, not a header*name*

**Comment by mskucherawy** [comment]
This isn't the right fix.  Working on it now.

**Comment by mskucherawy** [comment]
Fixed by commit 783f4475291c9c2393e37ead83947dcad4706982.
