### ISSUE TITLE
Flags for inbound (verify seal) and outbound (generate new seal) milter processing

### ISSUE THREAD

**Issue by AntiFreeze** [trusteddomainproject/OpenARC#12]
OpenARC cannot validate and sign a message in the same milter pass as one would naively hope, as validation must occur before a message is modified, and signing cannot occur until after the message is modified. Therefore, OpenARC needs the ability to run in two passes, one for inbound messages (validation and stamping of Authentication Results), and one for outbound messages (applying a seal).

**Notes:**

* The current openarc milter runs validate/sign in one pass
* This could mean either milter logic that determines which pass to run, or
* More likely just a command line option that specifies which mode to run in (which would result in two running milters)

**Acceptance Criteria:**

* OpenARC milters where message modification can be sandwiched between passes properly

**Comment by mskucherawy** [comment]
Probably use OpenDKIM's simple sign/verify criteria.

**Comment by AntiFreeze** [comment]
Agreed, let's use the same sign/verify criteria, including milter options so the suite can be run on different hosts.
