### ISSUE TITLE
Make sure running openarc with the verification flag set has the appropriate output

### ISSUE THREAD

**Issue by AntiFreeze** [trusteddomainproject/OpenARC#13]
As a user testing message verification from the CLI (or a test suite reading output from the CLI), I want a clear understanding of verification state.

**Notes:**

* Right now the verification flag returns the milter state (if verbosity is on) and nothing else, but should be returning either just the cv value or the updated headers where the cv value can be read from.
* The exact syntax we're talking about is: openarc -c openarc.conf -f -l -v -t [msgfile]
* the expected output should be the message with updated headers (i.e. the output that would be returned via the milter), but this is not the case currently

**Acceptance Criteria:**

* Running openarc with the verification flag should produce useful output to know the verification status

**Comment by mskucherawy** [comment]
I think you want something equivalent to opendkim-testmsg, with a flag that prints the chain validation status on completion.  We should leave "openarc -t" as is because its specific purpose is to do milter-style things.

**Comment by geneshuman** [comment]
This issue should be closed.  You can get eveything you want by parsing the output of passing -v -v to the command.
