### ISSUE TITLE
Hardfails should be softened and instead set cv values properly

### ISSUE THREAD

**Issue by AntiFreeze** [trusteddomainproject/OpenARC#14]
OpenARC should never hardfail, it should only set the cv= value appropriately and move on.

**Notes:**

* OpenARC aborts in some instances where a message fails validation.
* Instead, ARC should set the cv to fail or invalid as appropriate.
* Some of these aborts appear to happen well before chain validation even begins

**Acceptance Criteria:**

* OpenARC should never abort early due to ARC-specific issues, failures therein should results in cv=fail or cv=invalid

**Out of Scope:**

* Any other reasons for openarc aborting early that aren't directly related to setting a cv value more appropriately

**Comment by mskucherawy** [comment]
It seems odd to go through all kinds of crypto work merely to affix a "cv=invalid" for a malformed seal.  Maybe we should just attach a regular AR field for this case?

Poked the DMARC list for consensus.
