### ISSUE TITLE
Make AMS h= headers configurable

### ISSUE THREAD

**Issue by AntiFreeze** [trusteddomainproject/OpenARC#15]
OpenARC should allow the headers covered by the AMS to be configurable.

**Notes:**

* Right now, openarc uses the h= tag from the last arc set, or all headers currently in the message, when generating the h= tag for the current AMS.
* The list of headers to sign should be configurable as it is with opendkim
* Per spec, ARC Seal should never be covered by the AMS h= tag

**Acceptance Criteria:**

* Headers can be specified via config file

**Comment by mskucherawy** [comment]
Yes we should do this.
