### ISSUE TITLE
Minimal white list/reputation functionality for final receivers

### ISSUE THREAD

**Issue by AntiFreeze** [trusteddomainproject/OpenARC#19]
As a small or corporate receiver at the last hop with no other arc-aware software in my world, I want the option to have openarc drop failed messages the same way opendmarc does.

**Notes:**

* This would be accomplished through a configuration option
* There would be a simple whitelist of known intermediaries provided
* The message would be dropped if:
  * The chain state is not pass
  * There is a signatory not on the whitelist
  * The chain state is pass, all signatories are on the white list, but the initial DMARC disposition of the message was reject.

**Acceptance Criteria:**

* A receiver can configure an option, modify a whitelist, and openarc will properly drop bad chains, messages signed by untrusted parties, or messages whose initial dmarc disposition was a reject.

**Out of Scope:**

* Collecting an initial whitelist
* Handling quarantine or any other message rejection criteria outside the scope above
* Smarter AAR inspection for dmarc disposition than defined above

**Comment by xpunkt** [comment]
imho opendmarc would use openarc results in newer versions of opendmarc ?

so reject policy stay at opendmarc, not other milters 

i like the repution idea still :)

**Comment by AntiFreeze** [comment]
Support for this has been moved to OpenDMARC:
- https://github.com/trusteddomainproject/OpenDMARC/pull/5
- https://github.com/trusteddomainproject/OpenDMARC/pull/6
- https://github.com/trusteddomainproject/OpenDMARC/pull/7
