### ISSUE TITLE
Messages with multiple incoming AR headers generate empty b= values in the AMS

### ISSUE THREAD

**Issue by AntiFreeze** [trusteddomainproject/OpenARC#24]
Steps to reproduce:

1) Have 3 milters in sendmail in the following order: opendkim, opendmarc, openarc

2) Send a message from the box

3) You'll receive a message with an AMS that ends with "b="

4) Turn off opendkim and opendmarc

5) Send a message

6) Get an AMS with a b= payload as expected

**Comment by geneshuman** [comment]
Having a specific message that, when fed into openarc produces this effect would be incredibley helpful

**Comment by AntiFreeze** [comment]
I didn't add one because I wasn't certain how the validation and signing fixes would affect this. I can attempt to reproduce tomorrow and attach a message if it still fails.

**Comment by juh** [comment]
Might be the same as #44
