### ISSUE TITLE
OpenARC continues to sign failing chains 

### ISSUE THREAD

**Issue by geneshuman** [trusteddomainproject/OpenARC#76]
The following test of the signing ARC test suite fails:

no_additional_sig

When an intermediary encounters an ARC chain that has been marked as failing by a previous intermediary, it is not supposed to continue adding ARC sets to the chain.

**Comment by spkjp** [comment]
Commit 60ad11ef22b239cf830f860b62b1b18b0a2e558a seems to have taken care of this.
