### ISSUE TITLE
Validation test suite failures

### ISSUE THREAD

**Issue by geneshuman** [trusteddomainproject/OpenARC#78]
The following 5 tests from the validation test suite fail, however the reasons this is the case has not been isolated:

AssertionError: 'fail' != ''
 : cv_fail_i1_as_cv_fail

AssertionError: 'fail' != ''
 : cv_fail_i2_as2_fail

AssertionError: 'fail' != ''
 : cv_fail_i2_as1_fail

AssertionError: '' != 'none'
: cv_no_headers

AssertionError: '' != 'none'
: cv_empty

**Comment by AntiFreeze** [comment]
These are issues with the test suite, not with openarc, and they already exist as open issues with simple fixes there. Closing.
