### ISSUE TITLE
OpenARC memory leak

### ISSUE THREAD

**Issue by AntiFreeze** [trusteddomainproject/OpenARC#81]
Several parties have reported easily noticeable memory leaks from OpenARC.

Juan Pizzorno submitted a PR a while back to help address (that I can't seem to find now), and Jered Floyd posted a message earlier this week to openarc-users with details as well.

**Comment by kurta** [comment]
On Fri, Feb 23, 2018 at 8:05 AM, Seth Blank <notifications@github.com>
wrote:

> Several parties have reported easily noticeable memory leaks from OpenARC.
>
> Juan Pizzorno submitted a PR a while back to help address (that I can't
> seem to find now), and Jered Floyd posted a message earlier this week to
> openarc-users with details as well.
>
I think that you're thinking of #68.

--Kurt

**Comment by spkjp** [comment]
I've now submitted #86 (how cute, it's the reverse of my previous #68) with various additional memory leak fixes.
