### ISSUE TITLE
HAVE_OPENSSL_STRDUP broken

### ISSUE THREAD

**Issue by jaltmayerpizzorno** [trusteddomainproject/OpenARC#94]
`OPENSSL_strdup` is a macro around `CRYPTO_strdup`, so `AC_SEARCH_LIBS`
in `configure.ac` can't find it.  In any case, the code can't simply revert to the
standard library's `strdup`, as the OpenSSL libraries may/do add debugging
information around memory allocations and deallocations... the fallback code
must use OpenSSL allocation functions instead.  I suggest seeing if the version
of OpenSSL that doesn't have `OPENSSL_strdup` has `CRYPTO_strdup` and
switch all those `OPENARC_malloc`, etc. to use `CRYPTO_...` instead.

**Comment by jaltmayerpizzorno** [comment]
My fix is in https://github.com/trusteddomainproject/OpenARC/pull/96

**Comment by AntiFreeze** [comment]
#96 was merged last month.
